[package]
name = "apalis-pgmq"
version = "0.1.0-rc.5"
authors = ["Njuguna Mureithi <mureithinjuguna@gmail.com>"]
edition = "2024"
repository = "https://github.com/apalis-dev/apalis-pgmq"
license = "PostgreSQL"
description = "Background task processing for rust using apalis and pgmq"
readme = "README.md"
homepage = "https://github.com/apalis-dev/apalis-pgmq"
documentation = "https://docs.rs/apalis-pgmq"
keywords = ["apalis", "postgres", "messages", "queue", "worker"]
categories = ["asynchronous", "database", "network-programming"]

[features]
default = ["tokio-comp"]
async-std-comp = ["async-std", "sqlx/runtime-async-std", "sqlx/tls-rustls"]
async-std-comp-native-tls = [
    "async-std",
    "sqlx/runtime-async-std",
    "sqlx/tls-native-tls",
]
tokio-comp = ["tokio", "sqlx/runtime-tokio", "sqlx/tls-rustls"]
tokio-comp-native-tls = ["tokio", "sqlx/runtime-tokio", "sqlx/tls-native-tls"]

### By default messages are stored as JSON in pgmq schema
bytes-compat = [] # messages will stored as BYTEA in apalis_pgmq schema 

[dependencies]
sqlx = { version = "0.9.0", features = ["postgres", "json"] }
apalis-core = { version = "1.0.0-rc.10", default-features = false, features = [
    "sleep",
] }
apalis-codec = { version = "0.1.0-rc.10", default-features = false, features = [
    "json",
] }

thiserror = "2.0.21"
url = "2.5.8"
tracing = "0.1.44"
futures = "0.3.34"
serde = "1.0.229"
serde_json = "1.0.151"
pin-project-lite = "0.2.17"
tokio = { version = "1", features = [
    "rt",
    "net",
], optional = true, default-features = false }
async-std = { version = "1.13.2", optional = true, default-features = false }
pgmq = { version = "0.33.7", features = ["install-sql"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
apalis = { version = "1.0.0-rc.10" }
apalis-workflow = { version = "0.1.0-rc.10" }
facet = "0.46.5"
facet-msgpack = "0.46.1"

[[example]]
name = "codec"
required-features = ["bytes-compat"]
